# Formes parlées pour l'audio (français, allemand) — même ordre que vocab_kapitel1.py
# Les abréviations du manuel (etw., jn, (A), (D), *, (-en), ≠, →) sont développées à l'oral.

SPOKEN = [
    ("manger", "essen"),
    ("boire", "trinken"),
    ("le pain", "das Brot"),
    ("la viande, le poisson", "das Fleisch, der Fisch"),
    ("l'œuf", "das Ei"),
    ("la cerise", "die Kirsche"),
    ("J'aime les légumes. J'aime les fruits.", "Ich mag Gemüse. Mir schmecken Früchte."),
    ("C'est bon ! C'est délicieux !", "Das schmeckt gut! Das schmeckt lecker!"),
    ("le plat préféré", "das Lieblingsessen, das Lieblingsgericht"),
    ("aimer manger, préférer manger, aimer par-dessus tout manger", "etwas gern essen, lieber essen, am liebsten essen"),
    ("la moutarde", "der Senf"),
    ("la spécialité", "die Spezialität"),
    ("la cuisine ; cuisiner", "die Küche; kochen"),
    ("la restauration rapide", "das Fastfood"),
    ("le plat", "das Gericht"),
    ("des plats sucrés ou salés, légers ou consistants", "süße oder salzige, leichte oder deftige Gerichte"),
    ("l'entrée, le plat principal, le dessert", "die Vorspeise, die Hauptspeise, die Nachspeise, das Dessert"),
    ("la boisson", "das Getränk"),
    ("le kebab", "der Döner"),
    ("le snack", "der Snack"),
    ("le repas rapide, le snack-bar", "der Imbiss"),
    ("goûter quelque chose", "etwas kosten, etwas probieren"),
    ("la recette ; les ingrédients", "das Rezept; die Zutaten"),
    ("être végétarien, être végan", "Vegetarier sein, Veganer sein"),
    ("montrer quelque chose", "etwas zeigen"),
    ("aller avec quelque chose, correspondre à quelque chose", "zu etwas passen, zu etwas gehören"),
    ("l'immigration", "die Einwanderung, die Immigration"),
    ("l'immigré", "der Einwanderer"),
    ("venir de, être originaire de", "kommen aus, stammen aus"),
    ("le pays d'origine, la patrie", "die Heimat"),
    ("apporter quelque chose", "etwas bringen"),
    ("le pays d'origine, le pays de provenance", "das Herkunftsland"),
    ("l'échange culinaire", "der kulinarische Austausch"),
    ("l'Histoire", "die Geschichte"),
    ("l'État multinational", "der Vielvölkerstaat"),
    ("la diversité", "die Vielfalt"),
    ("divers, varié", "vielfältig"),
    ("différent", "unterschiedlich"),
    ("le miracle économique", "das Wirtschaftswunder"),
    ("le travailleur immigré", "der Gastarbeiter"),
    ("marquer, influencer quelque chose", "etwas prägen"),
    ("l'influence sur quelque chose", "der Einfluss auf etwas"),
    ("influencer quelqu'un ou quelque chose", "jemanden oder etwas beeinflussen"),
    ("le café, la boisson", "der Kaffee"),
    ("le café, l'établissement", "das Kaffeehaus, das Café"),
    ("le client", "der Kunde, der Gast"),
    ("le serveur", "der Kellner"),
    ("commander quelque chose", "etwas bestellen"),
    ("le journal, le magazine", "die Zeitung, die Zeitschrift"),
    ("l'ambiance", "das Ambiente"),
    ("attirant", "attraktiv"),
    ("traditionnel, moderne", "traditionell, modern"),
    ("le souvenir de quelque chose", "die Erinnerung an etwas"),
    ("se souvenir de quelque chose", "sich an etwas erinnern"),
    ("changer quelque chose", "etwas ändern"),
    ("se mettre au goût du jour", "mit der Zeit gehen"),
    ("comparé à quelque chose", "im Vergleich zu etwas"),
    ("développer quelque chose", "etwas entwickeln"),
    ("l'invention", "die Erfindung"),
    ("environ", "rund, etwa, ungefähr"),
]
