# Wortschatz — Kapitel 1 · Kulinarische Vielfalt (p. 22)
# Chaque entrée : (allemand, français, section, niveau)

VOCAB = [
    # ── Essen und trinken ── A2
    ("essen*", "manger", "Essen und trinken", "A2"),
    ("trinken*", "boire", "Essen und trinken", "A2"),
    ("das Brot", "le pain", "Essen und trinken", "A2"),
    ("das Fleisch / der Fisch", "la viande / le poisson", "Essen und trinken", "A2"),
    ("das Ei (-er)", "l'œuf", "Essen und trinken", "A2"),
    ("die Kirsche (-n)", "la cerise", "Essen und trinken", "A2"),
    ("Ich mag Gemüse. / Mir schmecken Früchte.", "J'aime les légumes / les fruits.", "Essen und trinken", "A2"),
    ("Das schmeckt gut / lecker!", "C'est bon / délicieux !", "Essen und trinken", "A2"),
    ("das Lieblingsessen / Lieblingsgericht", "le plat préféré", "Essen und trinken", "A2"),
    ("etw. gern → lieber → am liebsten essen*", "aimer → préférer manger qc", "Essen und trinken", "A2"),
    ("der Senf", "la moutarde", "Essen und trinken", "A2"),
    ("die Spezialität (-en)", "la spécialité", "Essen und trinken", "A2"),
    ("die Küche (-n) ; kochen", "la cuisine ; cuisiner", "Essen und trinken", "A2"),
    ("das Fastfood", "la restauration rapide", "Essen und trinken", "A2"),
    # ── Essen und trinken ── A2/B1
    ("das Gericht (-e)", "le plat", "Essen und trinken", "A2/B1"),
    ("süße ≠ salzige ; leichte ≠ deftige Gerichte", "des plats sucrés ≠ salés ; légers ≠ consistants", "Essen und trinken", "A2/B1"),
    ("die Vorspeise ; die Hauptspeise ; die Nachspeise = das Dessert", "l'entrée ; le plat principal ; le dessert", "Essen und trinken", "A2/B1"),
    ("das Getränk (-e)", "la boisson", "Essen und trinken", "A2/B1"),
    ("der Döner", "le kebab", "Essen und trinken", "A2/B1"),
    ("der Snack", "le snack", "Essen und trinken", "A2/B1"),
    ("der Imbiss", "le repas rapide, le snack ; le snack-bar", "Essen und trinken", "A2/B1"),
    ("etw. kosten = probieren", "goûter qc", "Essen und trinken", "A2/B1"),
    ("das Rezept ; die Zutaten", "la recette ; les ingrédients", "Essen und trinken", "A2/B1"),
    ("Vegetarier(in) / Veganer(in) sein", "être végétarien(ne) / végan(e)", "Essen und trinken", "A2/B1"),
    ("etw. zeigen", "montrer qc", "Essen und trinken", "A2/B1"),
    ("zu etw. (D) passen / zu etw. (D) gehören", "aller avec qc / correspondre à qc", "Essen und trinken", "A2/B1"),
    # ── Immigration und Austausch ── A2
    ("die Einwanderung = die Immigration", "l'immigration", "Immigration und Austausch", "A2"),
    ("der Einwanderer (-)", "l'immigré", "Immigration und Austausch", "A2"),
    ("aus … kommen* / stammen", "venir / être originaire de…", "Immigration und Austausch", "A2"),
    ("die Heimat", "le pays d'origine", "Immigration und Austausch", "A2"),
    ("etw. bringen*", "apporter qc", "Immigration und Austausch", "A2"),
    # ── Immigration und Austausch ── A2/B1
    ("das Herkunftsland", "le pays d'origine", "Immigration und Austausch", "A2/B1"),
    ("der (kulinarische) Austausch", "l'échange (culinaire)", "Immigration und Austausch", "A2/B1"),
    ("die Geschichte", "l'Histoire", "Immigration und Austausch", "A2/B1"),
    ("der Vielvölkerstaat", "l'État multinational", "Immigration und Austausch", "A2/B1"),
    ("die Vielfalt", "la diversité", "Immigration und Austausch", "A2/B1"),
    ("vielfältig", "divers, varié", "Immigration und Austausch", "A2/B1"),
    ("unterschiedlich", "différent", "Immigration und Austausch", "A2/B1"),
    ("das Wirtschaftswunder", "le miracle économique", "Immigration und Austausch", "A2/B1"),
    ("der Gastarbeiter (-)", "le travailleur immigré", "Immigration und Austausch", "A2/B1"),
    ("etw. prägen", "marquer, influencer qc", "Immigration und Austausch", "A2/B1"),
    ("der Einfluss (¨e) auf etw. (A)", "l'influence sur qc", "Immigration und Austausch", "A2/B1"),
    ("jn / etw. beeinflussen", "influencer qn / qc", "Immigration und Austausch", "A2/B1"),
    # ── Kaffeehauskultur ── A2
    ("der Kaffee", "le café (la boisson)", "Kaffeehauskultur", "A2"),
    ("das Kaffeehaus = das Café", "le café (l'établissement)", "Kaffeehauskultur", "A2"),
    ("der Kunde (-n) ; der Gast (¨e)", "le client", "Kaffeehauskultur", "A2"),
    ("der Kellner (-)", "le serveur", "Kaffeehauskultur", "A2"),
    ("etw. bestellen", "commander qc", "Kaffeehauskultur", "A2"),
    ("die Zeitung (-en) / die Zeitschrift (-en)", "le journal / le magazine", "Kaffeehauskultur", "A2"),
    ("das Ambiente", "l'ambiance", "Kaffeehauskultur", "A2"),
    ("attraktiv", "attirant", "Kaffeehauskultur", "A2"),
    ("traditionell ≠ modern", "traditionnel ≠ moderne", "Kaffeehauskultur", "A2"),
    # ── Kaffeehauskultur ── A2/B1
    ("die Erinnerung (-en) an etw. (A)", "le souvenir de qc", "Kaffeehauskultur", "A2/B1"),
    ("sich an etw. (A) erinnern", "se souvenir de qc", "Kaffeehauskultur", "A2/B1"),
    ("etw. ändern", "changer qc", "Kaffeehauskultur", "A2/B1"),
    ("mit der Zeit gehen*", "se mettre au goût du jour", "Kaffeehauskultur", "A2/B1"),
    ("im Vergleich zu etw. (D)", "comparé à qc", "Kaffeehauskultur", "A2/B1"),
    ("etw. entwickeln", "développer qc", "Kaffeehauskultur", "A2/B1"),
    ("die Erfindung (-en)", "l'invention", "Kaffeehauskultur", "A2/B1"),
    ("rund, etwa, ungefähr", "environ", "Kaffeehauskultur", "A2/B1"),
]
